version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
    volumes:
      - "./pgdata:/var/lib/postgresql/data"
  web:
    build: ./code
    command: bundle exec rails s -b '0.0.0.0'
    volumes:
      - "./code:/rails-docker"
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true
    stdin_open: true    
